apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubediskguard
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch"] 