apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubediskguard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubediskguard
subjects:
  - kind: ServiceAccount
    name: kubediskguard
    namespace: kube-system 