# KubeDiskGuard 配置文件示例
# 使用方法：
# 1. 复制此文件为 config.yaml
# 2. 设置环境变量 CONFIG_FILE_PATH=/path/to/config.yaml
# 3. 启动应用程序，修改此文件内容将自动重新加载配置

# 基础配置
monitorInterval: "30s"          # 监控间隔
diskUsageThreshold: 0.85         # 磁盘使用率阈值 (85%)
logLevel: "info"                 # 日志级别
enableMetrics: true              # 是否启用指标收集
metricsPort: 8080               # 指标服务端口

# Kubernetes 配置
kubeconfig: ""                   # kubeconfig 文件路径，空表示使用集群内配置
namespace: "default"             # 监控的命名空间

# 容器运行时配置
containerRuntime: "containerd"   # 容器运行时类型 (docker/containerd)
containerdSocket: "/run/containerd/containerd.sock"  # containerd socket 路径
dockerSocket: "/var/run/docker.sock"                # docker socket 路径

# IOPS 限制配置
defaultReadIOPS: 1000           # 默认读 IOPS 限制
defaultWriteIOPS: 1000          # 默认写 IOPS 限制
maxReadIOPS: 10000              # 最大读 IOPS 限制
maxWriteIOPS: 10000             # 最大写 IOPS 限制

# 智能速率限制配置
windowConfig:
  enabled: true                  # 是否启用智能速率限制
  windowSize: "5m"              # 时间窗口大小
  maxRequestsPerWindow: 100     # 每个时间窗口最大请求数
  burstSize: 10                 # 突发请求大小
  
# 高级配置
advancedConfig:
  enableCgroupV2: true          # 是否启用 cgroup v2 支持
  enablePodAnnotations: true    # 是否启用 Pod 注解支持
  enableNodeSelector: false    # 是否启用节点选择器
  retryAttempts: 3             # 重试次数
  retryDelay: "1s"             # 重试延迟
  
# 安全配置
securityConfig:
  enableTLS: false             # 是否启用 TLS
  certFile: ""                 # TLS 证书文件路径
  keyFile: ""                  # TLS 私钥文件路径
  enableAuth: false            # 是否启用认证
  
# 性能调优配置
performanceConfig:
  maxConcurrentOperations: 50  # 最大并发操作数
  operationTimeout: "30s"      # 操作超时时间
  enableProfiling: false       # 是否启用性能分析
  gcPercent: 100               # GC 百分比